### ISSUE TITLE
Flatten source code hierarchy

### ISSUE THREAD

**Issue by akohlmey** [TempleHPC/maui-scheduler#34]
As we clean up the maui code and remove unused or undesired segment, there is little reason to keep the three source code folders separate and build three libraries. instead, it would be sufficient to have all C sources in src/ and the include files in include/ and then build only one library libmaui.a. That should also simplyfy resolving issue #5.

**Comment by rbberger** [comment]
See e4f7cb7ec23e35e153ac500007d76e7a6b969577
